sudo: required
dist: trusty
language: c++

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - STD=c++98
  - STD=c++03
  - STD=c++11
  - STD=c++14
  - STD=c++1z


matrix:
  exclude:
  - compiler: gcc
    env: STD=c++14
  - compiler: gcc
    env: STD=c++1z
    
script:
  - autoconf
  - ./configure
  - make test

