sudo: required
dist: trusty
language: c++

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - valgrind

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install valgrind; fi


env:
  - STD=c++98
  - STD=c++03
  - STD=c++11
  - STD=c++14
  - STD=c++1z


matrix:
  exclude:
  - os: linux
    env: STD=c++14
  - os: linux
    env: STD=c++1z
    
script:
  - autoconf
  - ./configure
  - make test

